### ISSUE TITLE
Support for reading / publishing of local binary files

### ISSUE THREAD

**Issue by jwnmulder** [jwnmulder/dbus2mqtt#21]
**Is your feature request related to a problem? Please describe.**
Firefox + MPRIS exposes  the `mpris:Arturl` property which has a reference like `file:///home/.../.mozilla/firefox/firefox-mpris/2_3.png`.

**Describe the solution you'd like**

Sometihng that integrates nicely with <https://www.home-assistant.io/integrations/image.mqtt/>

dbus2mqtt config could be something like

```yaml
         actions:
            - type: context_set
              context:
                artUrl: "{{ dbus_property_get(bus_name, path, 'org.mpris.MediaPlayer2.Player', 'Metadata', {}).get('mpris:artUrl') }}"
            - type: mqtt_publish
              topic: dbus2mqtt/org.mpris.MediaPlayer2/artUrlImage
              payload_type: binary
              payload_template: |
                {{ artUrl if artUrl and artUrl.startswith('file://') else None }}
````
