### ISSUE TITLE
Support for mute

### ISSUE THREAD

**Issue by jwnmulder** [jwnmulder/dbus2mqtt#24]
**Is your feature request related to a problem? Please describe.**
MPRIS does not implement a mute method. This can be simulated by storing the current volume, and setting it back to its original value

**Describe the solution you'd like**
A MQTT flow trigger that can listen on `mqtt_command_topic`.

Current volumne should be stored in a player specific context and not the global_context. global_context is for illustration only

```yaml
     flows:
        - name: "Mute / umute"
          triggers:
            - type: mqtt
              topic: dbus2mqtt/org.mpris.MediaPlayer2/command
              filter: "{{ json_value.command == 'mute' }}"
          actions:
            - type: context_set
              global_context:
                volume: "{{ dbus_property_get(mpris_bus_name, path, 'org.mpris.MediaPlayer2.Player', 'Volume', 1) }}"
            - type: dbus_property_set
              property: Volume
              value: >
                {{ 0 if args.mute else volume }}
```
