### ISSUE TITLE
Find solution for artUrl images for chromium snap

### ISSUE THREAD

**Issue by jwnmulder** [jwnmulder/dbus2mqtt#45]
**Describe the bug**

mpris:artUrl: file:///tmp/.org.chromium.Chromium.MWaq0H
Actual location due to snap: /tmp/snap-private-tmp/snap.chromium/tmp/.org.chromium.Chromium.MWaq0H

Elevated permissions required due to snap

**Comment by jwnmulder** [comment]
One way to get this working us to use docker-compose to mount the snap tmp folder and to use an additional dbus call to determine the /tmp folder

```yaml
services:
  dbus2mqtt:
    image: jwnmulder/dbus2mqtt
    command: "--config $HOME/.config/dbus2mqtt/config.yaml"
    volumes:
      # dbus2mqtt config file
      - "$HOME/.config/dbus2mqtt:$HOME/.config/dbus2mqtt:ro"
      # dbus access
      - "/run/user:/run/user:ro"
      
      - type: bind
        source: /tmp/snap-private-tmp/snap.chromium/tmp
        target: /tmp/snap-private-tmp/snap.chromium/tmp
        read_only: true
        bind:
          create_host_path: false
    environment:
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus"
      TZ: Europe/Amsterdam
    env_file: .env
    user: "1000:1000"
    privileged: true
    restart: unless-stopped
```

```yaml
dbus:
  subscriptions:

    - bus_name: org.freedesktop.DBus
      path: /org/freedesktop/DBus

    - bus_name: org.mpris.MediaPlayer2.*
      path: /org/mpris/MediaPlayer2
```

```yaml
            - type: context_set
              context:
                artUrl: "{{ (dbus_property_get(mpris_bus_name, mpris_path, 'org.mpris.MediaPlayer2.Player', 'Metadata') or {}).get('mpris:artUrl') if mpris_bus_name else None }}"
                connection_credentials: "{{ dbus_call('org.freedesktop.DBus', '/org/freedesktop/DBus', 'org.freedesktop.DBus', 'GetConnectionCredentials', [mpris_bus_name]) if mpris_bus_name else {} }}"
            - type: context_set
              context:
                security_label: "{{ (connection_credentials.LinuxSecurityLabel | b64decode).rstrip('\\x00') | default('') }}"
            - type: mqtt_publish
              topic: dbus2mqtt/org.mpris.MediaPlayer2/artUrlImage
              payload_type: binary
              payload_template: |
                {% if artUrl and artUrl.startswith('file://') %}
                  {% if security_label.startswith('snap.') %}
                    {{ 'file:///tmp/snap-private-tmp/' ~ security_label.split('.')[:2] | join('.') ~ artUrl[7:] }}
                  {% else %}
                    {{ artUrl }}
                  {% endif %}
                {% endif %}
```
