### ISSUE TITLE
MPRIS support for Kodi

### ISSUE THREAD

**Issue by jwnmulder** [jwnmulder/dbus2mqtt#47]
**Is your feature request related to a problem? Please describe.**

MPRIS integration for Kodi does expose an object on all paths causing path based navigation to fail when using introspection. Would be nice if similar to playerctl, path is taken as a given so we don't rely on path visiting using introspection.

Kodi plugin in use: [MediaPlayerRemoteInterface](https://github.com/wastis/MediaPlayerRemoteInterface)

This configuration will fail to pick up Kodi while playerctl is able todo so

```yaml
dbus:
  subscriptions:
    - bus_name: org.mpris.MediaPlayer2.*
      path: /org/mpris/MediaPlayer2
```

This works but causes signals to not match with '/'
```yaml
dbus:
  subscriptions:
    - bus_name: org.mpris.MediaPlayer2.*
      path: /
```

**Describe the solution you'd like**

Similar to playerctl, just assume that bus_names matching 'org.mpris.MediaPlayer2.*' always expose an interface on path '/org/mpris/MediaPlayer2'. So in that case we might want to not rely on introspection for path visiting
